### PR TITLE
apharo/remove node modules

### PR DESCRIPTION
**Pull request by asppsa**
- chore: remove node_modules from git
- chore: ignore node_modules
- chore: run npm install

### CODE REVIEW

**Review by Techn1x — APPROVED** [review]

**Comment by Techn1x** [comment]
I think this might have broken the step, not sure how though. Getting this error on all my PRs for this step...
https://github.com/blake-education/district-ui-client/runs/8075926608?check_suite_focus=true
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'esm'
Require stack:
- /home/runner/work/_actions/blake-education/ember-asset-size-action/main/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:66[7](https://github.com/blake-education/district-ui-client/runs/8075926608?check_suite_focus=true#step:4:8):27)
    at Module.require (internal/modules/cjs/loader.js:[8](https://github.com/blake-education/district-ui-client/runs/8075926608?check_suite_focus=true#step:4:9)87:1[9](https://github.com/blake-education/district-ui-client/runs/8075926608?check_suite_focus=true#step:4:10))
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/blake-education/ember-asset-size-action/main/index.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:[10](https://github.com/blake-education/district-ui-client/runs/8075926608?check_suite_focus=true#step:4:11)27:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:[12](https://github.com/blake-education/district-ui-client/runs/8075926608?check_suite_focus=true#step:4:13)) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/blake-education/ember-asset-size-action/main/index.js'
  ]
```

**Comment by Techn1x** [comment]
Based on some reading, I think it could be that we either need to keep node_modules here, or run npm install as part of the action or something. Am guessing the original creators has the node_modules as part of the repo for that reason :thinking: 

https://turus.ro/posts/node-js-error-cannot-find-module-insert-module-name

**Comment by Techn1x** [comment]
Looks like javascript-based github actions do need node_modules as part of the project

The reason for that seems to be an ongoing debate on the example "hello-world-javascript-action" project
https://github.com/actions/hello-world-javascript-action/issues/12

**Comment by Techn1x** [comment]
Apparently the other alternative is to compile the node_modules into a single file with https://github.com/vercel/ncc and check that in to the project, which is what github does with all their first party actions

Seems interesting but I think I'll just revert this PR and call it a day

**Comment by asppsa** [comment]
Oopsy - sorry for the trouble

**Comment by asppsa** [comment]
Chuck me a PR and I'll approve it @Techn1x

**Comment by Techn1x** [comment]
Revert PR https://github.com/blake-education/ember-asset-size-action/pull/12
Follow up PR to update node_modules https://github.com/blake-education/ember-asset-size-action/pull/13

**Comment by Techn1x** [comment]
> Oopsy - sorry for the trouble

no trouble at all! I learned stuff.

**Pull request merged**
